"""
Inference Script for Task 4: Real-World Health Data Project
Loads saved ML model pipeline from models/best_health_model.joblib
and predicts heart disease risk for a sample patient profile.

DISCLAIMER:
This inference script is built strictly for educational purposes and internship project demonstration.
Predictions generated by this model CANNOT replace clinical assessment by a licensed physician.
"""

import os
import sys
import pandas as pd
import joblib

# Ensure project root is in sys.path for joblib unpickling of custom classes
project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from src.preprocessing import CustomColumnTransformer
from src.train import MLPipeline, VectorizedLogisticRegression, VectorizedDecisionTree, VectorizedRandomForest, Node


def predict_health_risk(patient_profile: dict, model_path: str = None) -> dict:
    """Predict heart disease risk probability and diagnosis label for a patient dictionary."""
    if model_path is None:
        model_path = os.path.join(project_root, "models", "best_health_model.joblib")

    if not os.path.exists(model_path):
        raise FileNotFoundError(f"Model file not found at: {model_path}. Train model first!")

    model = joblib.load(model_path)
    df_input = pd.DataFrame([patient_profile])

    disease_pred = model.predict(df_input)[0]
    disease_proba = model.predict_proba(df_input)[0][1]

    result = {
        "predicted_diagnosis": "Heart Disease Present (1)" if disease_pred == 1 else "Normal / Low Risk (0)",
        "disease_risk_probability_pct": round(float(disease_proba) * 100, 2),
        "clinical_risk_tier": "High Risk" if disease_proba >= 0.6 else ("Moderate Risk" if disease_proba >= 0.3 else "Low Risk"),
        "disclaimer": "FOR EDUCATIONAL PURPOSES ONLY — NOT FOR MEDICAL DIAGNOSIS"
    }

    return result


if __name__ == "__main__":
    # Sample Patient Profile (High Risk profile: 58-year-old male, atypical chest pain, high blood pressure, ST depression)
    sample_patient = {
        "age": 58,
        "sex": 1,
        "cp": 2,
        "trestbps": 140,
        "chol": 240,
        "fbs": 0,
        "restecg": 1,
        "thalach": 120,
        "exang": 1,
        "oldpeak": 2.5,
        "slope": 1,
        "ca": 2,
        "thal": 3
    }

    print("==================================================")
    print("HEALTH RISK ANALYSIS & INFERENCE DEMO")
    print("==================================================")
    print("Input Patient Clinical Profile:")
    for k, v in sample_patient.items():
        print(f" - {k:15s}: {v}")

    prediction = predict_health_risk(sample_patient)
    print("\nModel Risk Prediction:")
    for k, v in prediction.items():
        print(f" - {k:28s}: {v}")
